### ISSUE TITLE
摘要里面是不能分段吗

### ISSUE THREAD

**Issue by GengchenXU** [summitgao/OUC-LaTex-bachelor#4]
试了不管是\par还是两个回车都是报错

**Comment by summitgao** [comment]
可以分段的 ~~~ 得自己想想办法

**Comment by GengchenXU** [comment]
谢谢老师已解决发自我的 iPhone在 2023年4月22日，11:47，Feng Gao ***@***.***> 写道：﻿
可以分段的 ~~~ 得自己想想办法
