### ISSUE TITLE
一级标题字号问题

### ISSUE THREAD

**Issue by Flanture** [summitgao/OUC-LaTex-bachelor#6]

**Comment by Flanture** [comment]
高老师您好，在中国海洋大学本科生毕业论文规范中说一级标题应该使用三号字体，二级标题应该使用四号字体，三级标题应该使用小四字体，这里是否写错了

**Comment by Flanture** [comment]
在oucart.cls中，
标题：\titleformat{\section} {\zihao{2}\heiti\raggedright} 表示一级标题使用二号黑体字。
子标题：\titleformat{\subsection} {\zihao{3}\heiti\raggedright} 表示二级标题使用三号黑体字。
子子标题：\titleformat{\subsubsection} {\zihao{4}\heiti\raggedright} 表示三级标题使用四号黑体字。

**Comment by summitgao** [comment]
> 在oucart.cls中， 标题：\titleformat{\section} {\zihao{2}\heiti\raggedright} 表示一级标题使用二号黑体字。 子标题：\titleformat{\subsection} {\zihao{3}\heiti\raggedright} 表示二级标题使用三号黑体字。 子子标题：\titleformat{\subsubsection} {\zihao{4}\heiti\raggedright} 表示三级标题使用四号黑体字。

抱歉，之前没有发现这个问题，未来考虑修正
